language: node_js
node_js:
  - "0.10"

before_script:
  - npm install -g istanbul
  - npm install -g karma
  - npm install -g karma-cli
  - npm install -g grunt-cli
  - npm install -g bower
  - npm install -g codeclimate-test-reporter

script:
  - bower install
  - grunt release
  - grunt comments:release
  - karma start config/karma.js --no-auto-watch --single-run

addons:
  code_climate:
    repo_token: 26927a8c0f4396bc55ee423a1c0df10cb09a6ee6bf838d4edc32df2432a069da

after_script:
  - cat "lcov.info" | codeclimate

git:
  depth: 10
